baseURL: /

publishDir: "public"
languageCode: en-us
title: "Data Rights for Digital Contact Tracing and Alerting"
theme: "dcta-datarights-theme"

canonifyURLs: true
enableRobotsTXT: true
sectionPagesMenu: main

params:
  ga_id: "UA-xxxxx-xx"
  description: ""
  author: "Harper Reed"
  keywords: ""
  cachebuster: ""
  name: "Data Rights for Digital Contact Tracing and Alerting"
  email: questions@dcta-datarights.org
  
disableKinds:
  - section
  - section
  - taxonomy
  - taxonomyTerm
  - rss
  - section
  - page

